package com.mall.pojo;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.type
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.father_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private Integer fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.logo
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.slogan
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String slogan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cat_image
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String catImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.bg_color
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String bgColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.type
     *
     * @return the value of category.type
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.type
     *
     * @param type the value for category.type
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.father_id
     *
     * @return the value of category.father_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.father_id
     *
     * @param fatherId the value for category.father_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.logo
     *
     * @return the value of category.logo
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.logo
     *
     * @param logo the value for category.logo
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.slogan
     *
     * @return the value of category.slogan
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.slogan
     *
     * @param slogan the value for category.slogan
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan == null ? null : slogan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cat_image
     *
     * @return the value of category.cat_image
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getCatImage() {
        return catImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cat_image
     *
     * @param catImage the value for category.cat_image
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setCatImage(String catImage) {
        this.catImage = catImage == null ? null : catImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.bg_color
     *
     * @return the value of category.bg_color
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getBgColor() {
        return bgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.bg_color
     *
     * @param bgColor the value for category.bg_color
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setBgColor(String bgColor) {
        this.bgColor = bgColor == null ? null : bgColor.trim();
    }
}