package com.mall.pojo;

import java.util.ArrayList;
import java.util.List;

public class OrderItemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public OrderItemsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("item_id like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("item_id not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemImgIsNull() {
            addCriterion("item_img is null");
            return (Criteria) this;
        }

        public Criteria andItemImgIsNotNull() {
            addCriterion("item_img is not null");
            return (Criteria) this;
        }

        public Criteria andItemImgEqualTo(String value) {
            addCriterion("item_img =", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgNotEqualTo(String value) {
            addCriterion("item_img <>", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgGreaterThan(String value) {
            addCriterion("item_img >", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgGreaterThanOrEqualTo(String value) {
            addCriterion("item_img >=", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgLessThan(String value) {
            addCriterion("item_img <", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgLessThanOrEqualTo(String value) {
            addCriterion("item_img <=", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgLike(String value) {
            addCriterion("item_img like", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgNotLike(String value) {
            addCriterion("item_img not like", value, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgIn(List<String> values) {
            addCriterion("item_img in", values, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgNotIn(List<String> values) {
            addCriterion("item_img not in", values, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgBetween(String value1, String value2) {
            addCriterion("item_img between", value1, value2, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemImgNotBetween(String value1, String value2) {
            addCriterion("item_img not between", value1, value2, "itemImg");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("item_name =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("item_name >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("item_name <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("item_name like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("item_name not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("item_name in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdIsNull() {
            addCriterion("item_spec_id is null");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdIsNotNull() {
            addCriterion("item_spec_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdEqualTo(String value) {
            addCriterion("item_spec_id =", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdNotEqualTo(String value) {
            addCriterion("item_spec_id <>", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdGreaterThan(String value) {
            addCriterion("item_spec_id >", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdGreaterThanOrEqualTo(String value) {
            addCriterion("item_spec_id >=", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdLessThan(String value) {
            addCriterion("item_spec_id <", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdLessThanOrEqualTo(String value) {
            addCriterion("item_spec_id <=", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdLike(String value) {
            addCriterion("item_spec_id like", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdNotLike(String value) {
            addCriterion("item_spec_id not like", value, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdIn(List<String> values) {
            addCriterion("item_spec_id in", values, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdNotIn(List<String> values) {
            addCriterion("item_spec_id not in", values, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdBetween(String value1, String value2) {
            addCriterion("item_spec_id between", value1, value2, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecIdNotBetween(String value1, String value2) {
            addCriterion("item_spec_id not between", value1, value2, "itemSpecId");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameIsNull() {
            addCriterion("item_spec_name is null");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameIsNotNull() {
            addCriterion("item_spec_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameEqualTo(String value) {
            addCriterion("item_spec_name =", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameNotEqualTo(String value) {
            addCriterion("item_spec_name <>", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameGreaterThan(String value) {
            addCriterion("item_spec_name >", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_spec_name >=", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameLessThan(String value) {
            addCriterion("item_spec_name <", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameLessThanOrEqualTo(String value) {
            addCriterion("item_spec_name <=", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameLike(String value) {
            addCriterion("item_spec_name like", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameNotLike(String value) {
            addCriterion("item_spec_name not like", value, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameIn(List<String> values) {
            addCriterion("item_spec_name in", values, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameNotIn(List<String> values) {
            addCriterion("item_spec_name not in", values, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameBetween(String value1, String value2) {
            addCriterion("item_spec_name between", value1, value2, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andItemSpecNameNotBetween(String value1, String value2) {
            addCriterion("item_spec_name not between", value1, value2, "itemSpecName");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andBuyCountsIsNull() {
            addCriterion("buy_counts is null");
            return (Criteria) this;
        }

        public Criteria andBuyCountsIsNotNull() {
            addCriterion("buy_counts is not null");
            return (Criteria) this;
        }

        public Criteria andBuyCountsEqualTo(Integer value) {
            addCriterion("buy_counts =", value, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsNotEqualTo(Integer value) {
            addCriterion("buy_counts <>", value, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsGreaterThan(Integer value) {
            addCriterion("buy_counts >", value, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_counts >=", value, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsLessThan(Integer value) {
            addCriterion("buy_counts <", value, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsLessThanOrEqualTo(Integer value) {
            addCriterion("buy_counts <=", value, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsIn(List<Integer> values) {
            addCriterion("buy_counts in", values, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsNotIn(List<Integer> values) {
            addCriterion("buy_counts not in", values, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsBetween(Integer value1, Integer value2) {
            addCriterion("buy_counts between", value1, value2, "buyCounts");
            return (Criteria) this;
        }

        public Criteria andBuyCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_counts not between", value1, value2, "buyCounts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_items
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 06 23:41:41 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_items
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}