package com.mall.pojo;

public class OrderItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.order_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.item_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.item_img
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String itemImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.item_name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.item_spec_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String itemSpecId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.item_spec_name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private String itemSpecName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.price
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.buy_counts
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    private Integer buyCounts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.id
     *
     * @return the value of order_items.id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.id
     *
     * @param id the value for order_items.id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.order_id
     *
     * @return the value of order_items.order_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.order_id
     *
     * @param orderId the value for order_items.order_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.item_id
     *
     * @return the value of order_items.item_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.item_id
     *
     * @param itemId the value for order_items.item_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.item_img
     *
     * @return the value of order_items.item_img
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getItemImg() {
        return itemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.item_img
     *
     * @param itemImg the value for order_items.item_img
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setItemImg(String itemImg) {
        this.itemImg = itemImg == null ? null : itemImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.item_name
     *
     * @return the value of order_items.item_name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.item_name
     *
     * @param itemName the value for order_items.item_name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.item_spec_id
     *
     * @return the value of order_items.item_spec_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getItemSpecId() {
        return itemSpecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.item_spec_id
     *
     * @param itemSpecId the value for order_items.item_spec_id
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setItemSpecId(String itemSpecId) {
        this.itemSpecId = itemSpecId == null ? null : itemSpecId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.item_spec_name
     *
     * @return the value of order_items.item_spec_name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public String getItemSpecName() {
        return itemSpecName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.item_spec_name
     *
     * @param itemSpecName the value for order_items.item_spec_name
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setItemSpecName(String itemSpecName) {
        this.itemSpecName = itemSpecName == null ? null : itemSpecName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.price
     *
     * @return the value of order_items.price
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.price
     *
     * @param price the value for order_items.price
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.buy_counts
     *
     * @return the value of order_items.buy_counts
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public Integer getBuyCounts() {
        return buyCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.buy_counts
     *
     * @param buyCounts the value for order_items.buy_counts
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    public void setBuyCounts(Integer buyCounts) {
        this.buyCounts = buyCounts;
    }
}