package com.mall.mapper;

import com.mall.pojo.Carousel;
import com.mall.pojo.CarouselExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    long countByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int deleteByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int insert(Carousel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int insertSelective(Carousel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    List<Carousel> selectByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    Carousel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByExampleSelective(@Param("row") Carousel row, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByExample(@Param("row") Carousel row, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByPrimaryKeySelective(Carousel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByPrimaryKey(Carousel row);
}