package com.mall.mapper;

import com.mall.pojo.ItemsSpec;
import com.mall.pojo.ItemsSpecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemsSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    long countByExample(ItemsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int deleteByExample(ItemsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int insert(ItemsSpec row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int insertSelective(ItemsSpec row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    List<ItemsSpec> selectByExample(ItemsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    ItemsSpec selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByExampleSelective(@Param("row") ItemsSpec row, @Param("example") ItemsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByExample(@Param("row") ItemsSpec row, @Param("example") ItemsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByPrimaryKeySelective(ItemsSpec row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbg.generated Thu Jul 06 23:41:41 CST 2023
     */
    int updateByPrimaryKey(ItemsSpec row);
}